Remove excluded architectures from simulator build
The removed instruction was preventing me from building for the
simulator on an x86 mac.

```
    ld: warning: Could not find or use auto-linked framework 'PurchasesCoreSwift'
    Undefined symbols for architecture arm64:
      "_OBJC_CLASS_$_RCCommonFunctionality", referenced from:
          objc-class-ref in PurchasesFlutterPlugin.o
      "_OBJC_CLASS_$_RCPurchases", referenced from:
          objc-class-ref in PurchasesFlutterPlugin.o
    ld: symbol(s) not found for architecture arm64
```

My own Podfile requires a different and apparently conflicting
instruction:

```rb
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
```

It's sad that we need these hacks at all, but it's better to keep the
hack outside the framework since your downstream users may need a
different hack depending on their system architecture.